### ISSUE TITLE
Depreciation of pip --no-binary

### ISSUE THREAD

**Issue by JeffreyBlinksma** [RobinsMediaTeam/Cardboard#53]
```
DEPRECATION: --no-binary currently disables reading from the cache of locally built wheels. In the future --no-binary will not influence the wheel cache. pip 23.1 will enforce this behaviour change. A possible replacement is to use the --no-cache-dir option. You can use the flag --use-feature=no-binary-enable-wheel-cache to test the upcoming behaviour. Discussion can be found at https://github.com/pypa/pip/issues/11453
```

**Comment by ThatOneNovaGuy** [comment]
`--no-binary` tag on line 7 has been removed and replaced with suggested `--no-cache-dir`, working on rewriting Dockerfile in `pip-dep-test` branch to resolve remaining errors.

**Comment by JeffreyBlinksma** [comment]
According to [pypa/pip issue #11453](https://github.com/pypa/pip/issues/11453#issue-1376757935) our specific usecase will still be supported.
> We want --no-binary to mean only one thing, namely "don't download wheels".
Since this is the reason we use `--no-binary`, this does not need to be changed in the code.

AKA: guess which two dumb fucks didn't read the docs? us. it was us.
-Nova
